services:
  spring-boot:
    build:
      context: .
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ${MAVEN_SETTINGS_FOLDER}:/root/.m2

  converter:
    image: johanekblad123/dc4eu-converter:latest
    ports:
      - "8090:8080"
